#!/bin/bash

# init.d file for podman service
# Credit to GERALD MÜCKE of DevCon5 for most of this
USER=$(id -nu)
if [[ -z "$XDG_RUNTIME_DIR" ]]; then
  export XDG_RUNTIME_DIR=/run/user/$UID
  if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
    export XDG_RUNTIME_DIR=/tmp/$USER-runtime
    if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
      mkdir -m 0700 "$XDG_RUNTIME_DIR"
    fi
  fi
fi

BASEPATH=${XDG_RUNTIME_DIR}/podman
PID_FILE=$BASEPATH/podman.pid
SOCK_FILE=$BASEPATH/podman.sock

start() {
  if [[ -S "$SOCK_FILE" || -f "$PID_FILE" ]]; then
    echo "podman service may already be running"
    return 1
  fi

  mkdir -p $BASEPATH
  podman system service --time=0 unix://$SOCK_FILE &
  echo "$!" > $PID_FILE
  echo "podman service started, pid is $(cat $PID_FILE)"

  counter=0
  until [[ -S "$SOCK_FILE" && "$counter" -lt 5 ]]
  do
    echo "waiting 1 second"
    sleep 1
    counter=$((counter+1))
  done

  chown -R "$(id -un):" $BASEPATH
  chmod g+rw $SOCK_FILE
}

stop() {
  if [ -S "$SOCK_FILE" ]; then
    echo "socket found"
  fi
  if [ -f "$PID_FILE" ]; then
    echo "pid file found, pid is $(cat $PID_FILE)"
  fi

  if [[ -S "$SOCK_FILE" && -f "$PID_FILE" ]]; then

       kill $(cat $PID_FILE)
       rm -f $SOCK_FILE
       rm -f $PID_FILE
  else
       echo "no socket found, Podman service seems to be stopped"
  fi
}

status() {
  if [[ -f "$PID_FILE" ]]; then
    pid=$(cat $PID_FILE)
    if [[ -S "$SOCK_FILE" && $(ps -p $pid > /dev/null) -eq 0 ]]; then
      echo "podman is running (PID=$pid)"
    else
      echo "podman is not running"
    fi
  else
    echo "podman is not started"
  fi

}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac